// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	ActivateUser(ctx context.Context, id int64) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DemoteUser(ctx context.Context, id int64) error
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListUsers(ctx context.Context) ([]User, error)
	PromoteUser(ctx context.Context, id int64) error
	SearchUsersByName(ctx context.Context, name string) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
